/*
Usage:

	aliaser [command] [flags]

Use "aliaser --help" for more information.
*/
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/aliaser/internal/cli"
)

// version is the application version injected at build time.
var version = "unknown - unofficial & generated by unknown"

// main is the entry point of the application.
func main() {
	if err := cli.New(version).Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)

		os.Exit(1)
	}

	os.Exit(0)
}
